- name: REDIS REPO FILE
  ansible.builtin.yum:
    name:  https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: present
    disable_gpg_check: true

- name: ENABLING REDIS 6.2 VERSION
  ansible.builtin.command: yum module enable redis:remi-6.2 -y

- name: INSTALLING REDIS
  ansible.builtin.yum:
    name: redis 
    state: present

- name: 
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: ENABLING AND STARTING THE REDIS
  ansible.builtin.service:
    name: redis
    state: started
    enabled: true

